version: "3"

services: 
  iptv-player:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=DOCKER
      - POSTGRESQL_DATABASE=iptv-player 
